import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar/Navbar";
import ClientOnly from "./components/ClientOnly";
import Modal from "./components/modals/Modal";

const nunito = Nunito({
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ClientOnly>
          <Modal 
            isOpen
            // onClose={() => {}}
            // onSubmit={() => {}}
            title='Title'
            body='Body'
            footer='Footer'
            actionLabel='Submit'
          />
          <Navbar />
        </ClientOnly>
        
        {children}
      </body>
    </html>
  );
}
